CREATE DATABASE IF NOT EXISTS cianp;
USE cianp;

CREATE TABLE IF NOT EXISTS usuario(
username VARCHAR(30) NOT NULL,
email VARCHAR(100) NOT NULL PRIMARY KEY UNIQUE,
cpf CHAR(11) NOT NULL UNIQUE,
prof VARCHAR(50),
data_nasc VARCHAR(30) NOT NULL,
parentesco VARCHAR(50) NOT NULL,
senha CHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS postagens(
id INT AUTO_INCREMENT PRIMARY KEY,
autor_email VARCHAR(100) NOT NULL,
user_name VARCHAR(30),
texto VARCHAR(1500) NOT NULL,
imagem1 VARCHAR(255) DEFAULT NULL,
imagem2 VARCHAR(255) DEFAULT NULL,
imagem3 VARCHAR(255) DEFAULT NULL,
FOREIGN KEY (autor_email) REFERENCES usuario(email)
);

CREATE TABLE IF NOT EXISTS comentarios(
id INT AUTO_INCREMENT PRIMARY KEY,
post_id INT NOT NULL,
autor_email VARCHAR(100) NOT NULL,
texto VARCHAR(300) NOT NULL,
FOREIGN KEY (post_id) REFERENCES postagens(id),
FOREIGN KEY (autor_email) REFERENCES usuario(email)
);

CREATE TABLE IF NOT EXISTS perguntas(
id int AUTO_INCREMENT PRIMARY KEY,
autor_email VARCHAR(100) NOT NULL,
user_name VARCHAR(100) NOT NULL,
texto VARCHAR(300) NOT NULL,
FOREIGN KEY (autor_email) REFERENCES usuario(email)
);

CREATE TABLE IF NOT EXISTS respostas_perguntas(
id INT AUTO_INCREMENT PRIMARY KEY,
id_perguntas INT NOT NULL,
autor_email VARCHAR(100) NOT NULL,
user_name VARCHAR(100) NOT NULL,
texto VARCHAR(300) NOT NULL,
FOREIGN KEY (id_perguntas) REFERENCES perguntas(id),
FOREIGN KEY (autor_email) REFERENCES usuario(email)
);